### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by impressivewebs** [ryanburgess/sassysass#32]
The website doesn't seem to work:

http://www.sassysass.com/

Is this project still supported?

**Comment by ryanburgess** [comment]
Thanks for catching that! The project is still supported. We just haven't added new features in awhile.

**Comment by ryanburgess** [comment]
Site is now back up http://www.sassysass.com/. Thanks for catching that.

**Comment by impressivewebs** [comment]
Ok, great, thanks!

**Comment by w4ilun** [comment]
@ryanburgess is the site static? Would you consider GitHub pages?

**Comment by ryanburgess** [comment]
@w4ilun it is really static. That's not a bad idea to move it to Github pages. I'll do that at some point.
