### ISSUE TITLE
PostCSS / CSSnext?

### ISSUE THREAD

**Issue by KingScooty** [ryanburgess/sassysass#8]
@ryanburgess, I'm gonna throw a big spanner in the works (sorry!). Would you ever consider moving from SASS to PostCSS / CSSnext? I've tried it out on a few projects at the BBC, and it's faster to compile, and way more readable as it's essentially just transpiling the future CSS spec into the current spec.

No worries if its out of scope as it's just my 2 cents. I may potentially fork and try it out.

**Comment by ryanburgess** [comment]
@KingScooty I think it's a great idea to build up this type of tool for PostCSS. It is impressive how fast it compiles and how easy it is to write. It would be great to include that as an option or even adding other CSS processors as options. Would that make sense?

**Comment by ryanburgess** [comment]
I'm going to close this issue for now because it's not in scope for the feature requests.
